---
title: "JuliaPlay"
output: html_document
editor_options: 
  chunk_output_type: console
---

Load packages
```{r}
library(lme4)
library(JuliaCall)
library(jglmm)
library(dplyr)
```

Open data
```{r}
#DF.w <- readRDS("data/DF.w.rds")
#DF.l.full <- readRDS("data/DF.l.full.rds")
#DF.l <- readRDS("data/DF.l.rds")
DF.l.inc <- readRDS("data/DF.l.inc.rds")
```

Set up Julia
```{r}
options(JULIA_HOME = "C:/Users/ncole/AppData/Local/Programs/Julia-1.6.2/bin/")
julia_setup()
julia_library("MixedModels")
```

```{r}
lm1 <- jglmm(Reaction ~ Days + (Days | Subject), lme4::sleepstudy)

lm1$model %>% summary()

```


```{r}

j$library("JellyMe4")
```


Junk
```{r}

## fit model
julia_assign("data", DF.l.inc)
julia_command("res = fit(MixedModel, 
                      @formula(happiness ~ trial * condition * image +
                               (1 | ResponseId) +
                               (1 + trial * image * condition | lab)), 
                      data)")
julia_command("tmp = ([res], [data])")

julia_eval("@rput tmp")
julia_eval('R"summary(tmp)"')

tmp <- as9

# combine model with dataset; then send back to R
julia_eval("tmp = ([res], [data])")
julia_command("as([tmp], "merModLmerTest")")
```

