---
title: 'Data Visualization Code for the Many Smiles Collaboration'
editor_options:
  chunk_output_type: console
---
## Setup R environment
```{r message = FALSE, results = "hide"}
# clear environment
rm(list = ls())

# install (if necessary) and load packages
  # function written by stevenworthington 
  Ipak <- function(pkg){
      new.pkg <- pkg[!(pkg %in% installed.packages()[, 'Package'])]
      
      if (length(new.pkg)) 
          install.packages(new.pkg, dependencies = TRUE)
      
      sapply(pkg, require, character.only = TRUE)
  }

  # vector of necessary packages
  packages <- c('tidyverse', 'ggplot2', 'ggtext', 'metafor',
                'ggpubr')
  
  # using vector of packages, call ipak function
  Ipak(packages)
  
  # delete vestigial
  rm(packages, Ipak)

# turn scientific notation off
options(scipen = 999)

# allow for Type III Sums of Square
options(contrasts = c('contr.sum', 'contr.poly'))

# set plotting options 
theme_set(theme_classic() +
          theme(strip.background = element_rect(fill = "gray35"),
                strip.text =element_text(colour = "white"),
                panel.border = element_blank(),
                legend.position = "none"
                )
          )
```

## Open data
```{r}
DF.w <- readRDS("data/processed/DF.w.rds")
DF.l.full <- readRDS("data/processed/DF.l.full.rds")
DF.l <- readRDS("data/processed/DF.l.rds")
DF.l.inc <- readRDS("data/processed/DF.l.inc.rds")
```

## Recode labels
DF.l
```{r}
DF.l <- DF.l %>%  
  mutate(trial = factor(trial,
                        levels = c("happy",
                                   "neutr",
                                   "fil.1",
                                   "fil.4")),
         trial = recode(trial,
                        fil.1 = "filler 1",
                        happy = "happy",
                        neutr = "neutral",
                        fil.4 = "filler 2"),
         condition = factor(condition,
                            levels = c("mimicry",
                                       "directd",
                                       "pentask")),
         condition = recode(condition,
                            directd = "voluntary facial action",
                            mimicry = "facial mimicry",
                            pentask = "pen-in-mouth"),
         image = recode(image,
                        absentt = "positive stimuli absent",
                        present = "positive stimuli present")
         )
```

DF.l.full
```{r}
DF.l.full <- DF.l.full %>%  
  mutate(trial = factor(trial,
                        levels = c("happy",
                                   "neutr",
                                   "fil.1",
                                   "fil.4")),
         trial = recode(trial,
                        fil.1 = "filler 1",
                        happy = "happy",
                        neutr = "neutral",
                        fil.4 = "filler 2"),
         condition = factor(condition,
                            levels = c("mimicry",
                                       "directd",
                                       "pentask")),
         condition = recode(condition,
                            directd = "voluntary facial action",
                            mimicry = "facial mimicry",
                            pentask = "pen-in-mouth"),
         image = recode(image,
                        absentt = "positive stimuli absent",
                        present = "positive stimuli present")
         )
```

DF.l.inc
```{r}
DF.l.inc <- DF.l.inc %>%  
  mutate(trial = factor(trial,
                        levels = c("happy",
                                   "neutr",
                                   "fil.1",
                                   "fil.4")),
         trial = recode(trial,
                        fil.1 = "filler 1",
                        happy = "happy",
                        neutr = "neutral",
                        fil.4 = "filler 2"),
         condition = factor(condition,
                            levels = c("mimicry",
                                       "directd",
                                       "pentask")),
         condition = recode(condition,
                            directd = "voluntary facial action",
                            mimicry = "facial mimicry",
                            pentask = "pen-in-mouth"),
         image = recode(image,
                        absentt = "positive stimuli absent",
                        present = "positive stimuli present")
         )
```


## Figure 2
```{r}
f2.DF <- DF.l.full %>%
  
  # apply inclusion criteria
  filter(inc == 1,
         inc.awa == 1)

png(filename = "output/figures/Figure2.png", 
    units = "in", 
    width = 7, 
    height = 4, 
    res = 300)

ggline(f2.DF, 
       x = "trial", y = "happiness", 
       add = c("mean_se"),
       facet.by = "condition",
       color = "image",
       palette = "jco") +
  theme_classic() +
  theme(strip.background = element_rect(fill = "gray35"),
        strip.text =element_text(colour = "white"),
        panel.border = element_blank(),
        legend.position= "top")

dev.off()

rm(f2.DF)
```

## Figure 3
Prepare dataframe
```{r}
f5.DF <- DF.l %>% 
  # select relevant variables
  select(ResponseId, trial, condition, 
         happiness, qulty_rate_var, 
         qulty_feel_var, qulty_smlr_var) %>% 
  
  # calculate a difference score between the happy and neutral poses☺
  pivot_wider(names_from = trial,
              values_from = happiness) %>%
  rowwise() %>% 
  mutate(happ.diff = happy - neutral) %>% 
  ungroup() %>% 
  
  # pivot longer so that there is one row for each moderator
  pivot_longer(cols = c(qulty_rate_var, 
                        qulty_smlr_var,
                        qulty_feel_var,
                        ),
               names_to = "mod") %>% 
  
  # relevel factors 
  mutate(mod = factor(mod,
                      levels = c("qulty_rate_var",
                                 "qulty_feel_var",
                                 "qulty_smlr_var")),
         mod = recode(mod,
                      qulty_rate_var = "compliance",
                      qulty_feel_var = "genuineness",
                      qulty_smlr_var = "similarity"))
```

For each task, specify modal response and when estimated effect of facial feedback became significant.

Note: these values are hard-coded, but code that shows how these values were derived is in ManySmiles_DataProcessing.Rmd
```{r}
f5.DF$sig.cross = as.numeric(NA)
f5.DF$mode = as.numeric(NA)

# compliance
f5.DF[f5.DF$condition == "facial mimicry" & 
      f5.DF$mod == "compliance", ]$sig.cross <- 5
f5.DF[f5.DF$condition == "facial mimicry" & 
       f5.DF$mod == "compliance", ]$mode <- 7

f5.DF[f5.DF$condition == "voluntary facial action" & 
      f5.DF$mod == "compliance", ]$sig.cross <- 5
f5.DF[f5.DF$condition == "voluntary facial action" & 
     f5.DF$mod == "compliance", ]$mode <- 7

f5.DF[f5.DF$condition == "pen-in-mouth" & 
      f5.DF$mod == "compliance", ]$sig.cross <- 6
f5.DF[f5.DF$condition == "pen-in-mouth" & 
      f5.DFz$mod == "compliance", ]$mode <- 7

# similarity
f5.DF[f5.DF$condition == "facial mimicry" & 
      f5.DF$mod == "similarity", ]$sig.cross <- 3
f5.DF[f5.DF$condition == "facial mimicry" & 
      f5.DF$mod == "similarity", ]$mode <- 6

f5.DF[f5.DF$condition == "voluntary facial action" & 
      f5.DF$mod == "similarity", ]$sig.cross <- 2
f5.DF[f5.DF$condition == "voluntary facial action" & 
      f5.DF$mod == "similarity", ]$mode <- 7

f5.DF[f5.DF$condition == "pen-in-mouth" & 
      f5.DF$mod == "similarity", ]$sig.cross <- 2
f5.DF[f5.DF$condition == "pen-in-mouth" & 
      f5.DF$mod == "similarity", ]$mode <- 6

# genuineness 
f5.DF[f5.DF$mod == "genuineness", ]$sig.cross <- 2

f5.DF[f5.DF$condition == "facial mimicry" & 
      f5.DF$mod == "genuineness", ]$mode <- 5
f5.DF[f5.DF$condition == "voluntary facial action" & 
      f5.DF$mod == "genuineness", ]$mode <- 5
f5.DF[f5.DF$condition == "pen-in-mouth" & 
      f5.DF$mod == "genuineness", ]$mode <- 1
```

Plot figure
```{r}
png(filename = "output/figures/Figure3.png", 
    units = "in", 
    height = 7, 
    width = 6.5, 
    res = 300)

ggplot(f5.DF, 
       aes(x = value, 
           y = happ.diff)) +
  facet_grid(cols = vars(condition),
             rows = vars(mod)) +
  geom_rect(aes(xmin = sig.cross - .25,
                xmax = 7.25,
                ymin = -6,
                ymax = 6),
            fill = "lightgreen",
            alpha = .01) +
  geom_rect(aes(xmin = mode - .25,
                xmax = mode + .25,
                ymin = -6,
                ymax = 6),
            fill = NA,
            colour = "black") + 
  geom_jitter(width = .1, 
              alpha = .2,
              colour = "dark grey") +
  geom_smooth(method = 'lm') +
  xlab("Self-reported rating") +
  ylab("Change in self-reported happiness") + 
  scale_x_continuous(
    breaks = c(1, 3, 5, 7))

dev.off()

rm(f5.DF)
```