---
title: 'Data Analysis Code for the Many Smiles Collaboration'
editor_options:
  chunk_output_type: console
---
## Setup R environment
```{r message = FALSE, results = "hide"}
# clear environment
rm(list = ls())

# install (if necessary) and load packages
  # function written by stevenworthington 
  Ipak <- function(pkg){
      new.pkg <- pkg[!(pkg %in% installed.packages()[, 'Package'])]
      
      if (length(new.pkg)) 
          install.packages(new.pkg, dependencies = TRUE)
      
      sapply(pkg, require, character.only = TRUE)
  }

  # vector of necessary packages
  packages <- c('tidyverse', 'ggplot2', 'lme4',
                #'lmerTest', 
                'emmeans', 'metafor',
                'ggtext')
  
  # using vector of packages, call ipak function
  Ipak(packages)
  
  # delete vestigial
  rm(packages, Ipak)

# turn scientific notation off
options(scipen = 999)

# allow for Type III Sums of Square
options(contrasts = c('contr.sum', 'contr.poly'))

# set plotting options 
theme_set(theme_classic() +
          theme(strip.background = 
                  element_rect(fill = "gray35"),
                strip.text = 
                  element_text(colour = "white"),
                panel.border = element_blank(),
                legend.position = "none"
                )
          )
```

## Open data
```{r}
DF.w <- readRDS("data/DF.w.rds")
DF.l.full <- readRDS("data/DF.l.full.rds")
DF.l <- readRDS("data/DF.l.rds")
DF.l.inc <- readRDS("data/DF.l.inc.rds")
```

## Data viz
Fix labels
```{r}
DF.viz <- 
  DF.l.inc %>%
  mutate(trial = factor(trial,
                        levels = c("neutr",
                                   "happy")),
         trial = recode(trial,
                        neutr = "neutral",
                        happy = "happy"),
         condition = factor(condition,
                            levels = c("mimicry",
                                       "directd",
                                       "pentask")),
         image = factor(image,
                        levels = c("present",
                                   "absentt")),
         condition = recode(condition,
                            directd = "voluntary facial action",
                            mimicry = "facial mimicry",
                            pentask = "pen-in-mouth"),
         image = recode(image,
                        present = "positive stimuli present",
                        absentt = "positive stimuli absent")
         )
```

### Main confirmatory
```{r}
# get descriptives
tmp <- DF.viz %>% 
  group_by(trial, condition, image) %>% 
  summarise(m = round(mean(happiness),
                      2),
            sd = round(sd(happiness),
                       2))

tmp2 <- DF.viz %>% 
  group_by(condition, image) %>%
  summarise(n = length(unique(ResponseId)))

tmp3 <- full_join(tmp, tmp2)
rm(tmp, tmp2)

# prepare plot  
png(filename = "figures/presentation/Figure1.png", 
    units = "in", 
    height = 7, 
    width = 6.5, 
    res = 300)

# plot
ggplot(DF.viz, 
       aes(x = trial, 
           y = happiness)) +
  # split plot by image and condition
  facet_grid(rows = vars(image),
             cols = vars(condition)) +
  
  # add jittered raw data
  geom_jitter(width = .1, 
              alpha = .07,
              colour = "dark grey") + 
  
  # connect participants' jittered raw data
  geom_line(alpha = .07, 
            aes(group = ResponseId),
            colour = "dark grey") +
  
  # add summary lines
  stat_summary(geom = "line",
               colour = "#3366FF",
               size = 1,
               aes(group = 1)) +
  
  stat_summary(colour = "#3366FF", 
               size = .5,
               fun = "mean") +
  
  # add task-specific M's and SDs
  geom_text(data = tmp3,
            aes(label = paste0("M = ", m,
                               "\n",
                               "SD = ", sd)),
            y = Inf,
            size = 2,
            vjust = 2) +
  
  # add condition-specific ns
  geom_text(data = tmp3,
            aes(label = paste0("n = ", n)),
            x = 2.5,
            y = Inf,
            size = 2,
            vjust = 2) +
  
  # adjust scales
  scale_x_discrete(
    expand = expand_scale(mult = c(.2, .2))) +
  
  scale_y_continuous(
    breaks = c(1, 3, 5, 7),
    expand = expand_scale(mult = c(0, .25))) +
  
  labs(y = "Self-reported happiness", 
       x = "Facial expression pose")

dev.off()
```

### Histogram
```{r}
# get data
DF.viz.2 <- DF.w %>% 
  #filter(condition == "pentask")
  mutate(condition = factor(condition,
                            levels = c("mimicry",
                                       "directd",
                                       "pentask")),
         condition = recode(condition,
                            directd = "voluntary facial action",
                            mimicry = "facial mimicry",
                            pentask = "pen-in-mouth"))

# calculate summary statistics
tmp <- DF.viz.2 %>% 
  group_by(condition) %>% 
  summarise(n = n(),
            m = round(mean(qulty_feel_var,
                           na.rm = T),
                      2),
            sd = round(sd(qulty_feel_var, 
                          na.rm = T),
                       2)
            )

# plot
png(filename = "figures/presentation/Figure3.png", 
       units = "in", 
       width = 6.4, 
       height = 7.2, 
       res = 300)


ggplot(DF.viz.2,
       aes(x = qulty_feel_var)) +
  
  facet_grid(cols = vars(condition))+
  
  # plot histogram (as percentage)
  geom_histogram(aes(y = stat(width*density)),
                 bins = 7,
                 fill = "gray60") +
  
  # add bin-specific percentage counts to histogram
  stat_bin(aes(y = stat(width*density),
               label = 
                 paste0((round(stat(width*density),
                               2) * 100),
                        "%")), 
           geom = "text",
           bins = 7,
           size = 3,
           vjust = -.5) +
  
  # paste descriptive statistics to left of histogram
  geom_text(data = tmp,
            aes(label = paste0("n = ", n,
                               "\n",
                               "M = ", m,
                               "\n",
                               "SD = ", sd)),
            x = 1,
            y = Inf,
            size = 3,
            hjust = 0,
            vjust = 1.25) +
  
  # fix scales
  scale_x_continuous(name = "Rating of extent to which pen-in-mouth smile felt 'genuine'",
                     breaks = c(1, 3, 5, 7)) +
  scale_y_continuous(expand = expand_scale(mult = c(0, .14)),
                     name = "Percent",
                     labels = scales::percent_format())

dev.off()
```

####
```{r}
# get data
DF.viz.2 <- DF.l %>%
  # pivot data wider
  pivot_wider(names_from = trial,
              values_from = happiness,
              id_cols = c(ResponseId,
                          country,
                          lab,
                          UserLanguage,
                          condition,
                          qulty_feel_var)) %>% 
  
  # filter
  # filter(condition == "pentask") %>% 
  
  # calculate pose effect
  rowwise() %>% 
  mutate(happ.diff = happy - neutr) %>% 
  ungroup()

# plot
png(filename = "figures/presentation/Figure4.png", 
       units = "in", 
       width = 6.4, 
       height = 7.2, 
       res = 300)

ggplot(DF.viz.2, 
       aes(x = qulty_feel_var, 
           y = happ.diff)) +
  facet_grid(cols = vars(condition))+
  geom_rect(aes(xmin = 2 - .25,
                xmax = 7.25,
                ymin = -4,
                ymax = 5),
            fill = "lightgreen",
            alpha = .01) +
  geom_rect(aes(xmin = 1 - .25,
                xmax = 1 + .25,
                ymin = -6,
                ymax = 6),
            fill = NA,
            colour = "black") + 
  geom_jitter(width = .1, 
              alpha = .2,
              colour = "dark grey") +
  geom_smooth(method = 'lm') +
  xlab("Rating of extent to which pen-in-mouth smile felt 'genuine'") +
  ylab("Change in self-reported happiness") + 
  scale_x_continuous(
    breaks = c(1, 3, 5, 7)) +
  ylim(-4, 5)

dev.off()

rm(DF.viz.2)
```


### Correlation graph
Create dataset for the data viz
```{r}
DF.viz <- DF.l %>% 
  # select relevant variables
  select(ResponseId, trial, condition, 
         happiness, 
         awareness, qulty_rate_var, 
         qulty_feel_var, qulty_smlr_var, 
         indiv_body) %>% 
  
  # calculate a difference score between the happy and neutral poses
  pivot_wider(names_from = trial,
              values_from = happiness) %>%
  rowwise() %>% 
  mutate(happ.diff = happy - neutr) %>% 
  ungroup() %>% 
  
  # relevel factors 
  mutate(condition = factor(condition,
                            levels = c("mimicry",
                                       "directd",
                                       "pentask")),
         condition = recode(condition,
                            directd = "voluntary facial action",
                            mimicry = "facial mimicry",
                            pentask = "pen-in-mouth"))
```

```{r}
DF.viz$sig.cross = 2
DF.viz$mode = as.numeric(NA)

# genuineness 
DF.viz[DF.viz$condition == "facial mimicry", ]$mode <- 5
DF.viz[DF.viz$condition == "voluntary facial action", ]$mode <- 5
DF.viz[DF.viz$condition == "pen-in-mouth", ]$mode <- 1
```

#### Part 1
```{r}
png(filename = "figures/presentation/Figure2.1.png", 
       units = "in", 
       width = 6.4, 
       height = 7.2, 
       res = 300)

ggplot(DF.viz, 
       aes(x = qulty_feel_var, 
           y = happ.diff)) +
  facet_grid(cols = vars(condition)) + 
  geom_jitter(width = .1, 
              alpha = .2,
              colour = "dark grey") +
  geom_smooth(method = 'lm') +
  xlab("Rating of extent to which pen-in-mouth smile felt 'genuine'") +
  ylab("Change in self-reported happiness") + 
  scale_x_continuous(
    breaks = c(1, 3, 5, 7))

dev.off()
```


```{r}
png(filename = "figures/presentation/Figure2.2.png", 
       units = "in", 
       width = 6.4, 
       height = 7.2, 
       res = 300)

ggplot(DF.viz, 
       aes(x = qulty_feel_var, 
           y = happ.diff)) +
  facet_grid(cols = vars(condition)) +
  geom_rect(aes(xmin = sig.cross - .25,
                xmax = 7.25,
                ymin = -6,
                ymax = 6),
            fill = "lightgreen",
            alpha = .01) +
  geom_jitter(width = .1, 
              alpha = .2,
              colour = "dark grey") +
  geom_smooth(method = 'lm') +
  xlab("Rating of extent to which pen-in-mouth smile felt 'genuine'") +
  ylab("Change in self-reported happiness") + 
  scale_x_continuous(
    breaks = c(1, 3, 5, 7))

dev.off()
```

```{r}
png(filename = "figures/presentation/Figure2.3.png", 
       units = "in", 
       width = 6.4, 
       height = 7.2, 
       res = 300)

ggplot(DF.viz, 
       aes(x = qulty_feel_var, 
           y = happ.diff)) +
  facet_grid(cols = vars(condition)) +
  geom_rect(aes(xmin = sig.cross - .25,
                xmax = 7.25,
                ymin = -6,
                ymax = 6),
            fill = "lightgreen",
            alpha = .01) +
  geom_rect(aes(xmin = mode - .25,
                xmax = mode + .25,
                ymin = -6,
                ymax = 6),
            fill = NA,
            colour = "black") + 
  geom_jitter(width = .1, 
              alpha = .2,
              colour = "dark grey") +
  geom_smooth(method = 'lm') +
  xlab("Rating of extent to which pen-in-mouth smile felt 'genuine'") +
  ylab("Change in self-reported happiness") + 
  scale_x_continuous(
    breaks = c(1, 3, 5, 7))

dev.off()
```
